version: "3"

services:
  next-app:
    image: nginx:alpine
    restart: always
    ports:
      - 80
      
    labels:
      - traefik.enable=true
      - traefik.http.routers.next-app.rule=Host(`next.woss.tech`)
      - traefik.http.routers.next-app.entrypoints=websecure
      - traefik.http.routers.next-app.tls.certResolver=letsencrypt
      - traefik.http.services.next-app.loadbalancer.server.port=3000
  # Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
