services:
  netdata:
    image: netdata/netdata
    pid: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.next-app-http.rule=Host(`next.woss.tech`)
      - traefik.http.routers.next-app-http.entrypoints=web
      - traefik.http.routers.next-app-http.middlewares=dokploy-redirect-to-https@docker
      - traefik.http.routers.next-app-https.rule=Host(`next.woss.tech`)
      - traefik.http.routers.next-app-https.entrypoints=websecure
      - traefik.http.routers.next-app-https.tls.certResolver=letsencrypt
      - traefik.http.services.next-app-svc.loadbalancer.server.port=19999
      - traefik.http.routers.next-app-https.service=next-app-svc
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

